/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSetupAdminRouteImport } from './routes/api/setup-admin'
import { Route as ApiDeleteClientRouteImport } from './routes/api/delete-client'
import { Route as ApiCreateClientRouteImport } from './routes/api/create-client'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupAdminRoute = ApiSetupAdminRouteImport.update({
  id: '/api/setup-admin',
  path: '/api/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteClientRoute = ApiDeleteClientRouteImport.update({
  id: '/api/delete-client',
  path: '/api/delete-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateClientRoute = ApiCreateClientRouteImport.update({
  id: '/api/create-client',
  path: '/api/create-client',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/create-client': typeof ApiCreateClientRoute
  '/api/delete-client': typeof ApiDeleteClientRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/create-client': typeof ApiCreateClientRoute
  '/api/delete-client': typeof ApiDeleteClientRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/create-client': typeof ApiCreateClientRoute
  '/api/delete-client': typeof ApiDeleteClientRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/api/create-client'
    | '/api/delete-client'
    | '/api/setup-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/api/create-client'
    | '/api/delete-client'
    | '/api/setup-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/api/create-client'
    | '/api/delete-client'
    | '/api/setup-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiCreateClientRoute: typeof ApiCreateClientRoute
  ApiDeleteClientRoute: typeof ApiDeleteClientRoute
  ApiSetupAdminRoute: typeof ApiSetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-admin': {
      id: '/api/setup-admin'
      path: '/api/setup-admin'
      fullPath: '/api/setup-admin'
      preLoaderRoute: typeof ApiSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-client': {
      id: '/api/delete-client'
      path: '/api/delete-client'
      fullPath: '/api/delete-client'
      preLoaderRoute: typeof ApiDeleteClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-client': {
      id: '/api/create-client'
      path: '/api/create-client'
      fullPath: '/api/create-client'
      preLoaderRoute: typeof ApiCreateClientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiCreateClientRoute: ApiCreateClientRoute,
  ApiDeleteClientRoute: ApiDeleteClientRoute,
  ApiSetupAdminRoute: ApiSetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
